/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cyberfox_util_platform_osx_NoNap */

#ifndef _Included_com_cyberfox_util_platform_osx_NoNap
#define _Included_com_cyberfox_util_platform_osx_NoNap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cyberfox_util_platform_osx_NoNap
 * Method:    nativeDontNapMeBro
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cyberfox_util_platform_osx_NoNap_nativeDontNapMeBro
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
